.TH "Dimension::tuple_diff< T,... >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::tuple_diff< T,... > \- Find the difference between two type-tuples\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP \fBT\fP, \fBtypename\fP \&.\&.\&.>
.br
struct Dimension::tuple_diff< T,\&.\&.\&. >"Find the difference between two type-tuples\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
