.TH "UnitTest/DimensionTest.h" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTest/DimensionTest.h
.SH SYNOPSIS
.br
.PP
\fR#include <gtest/gtest\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDimensionTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
