.TH "Dimension::MakeCountersImpl< std::tuple<>, std::tuple< UniqueTypes... > >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::MakeCountersImpl< std::tuple<>, std::tuple< UniqueTypes... > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DimensionUtilities\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBtype\fP = std::tuple<\fBtypename\fP std::tuple<\fBUniqueTypes\fP, \fBint\fP>\&.\&.\&.>"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename\&.\&.\&. UniqueTypes> \fBusing\fP \fBDimension::MakeCountersImpl\fP< std::tuple<>, std::tuple< UniqueTypes\&.\&.\&. > >::type = std::tuple<\fBtypename\fP std::tuple<\fBUniqueTypes\fP, \fBint\fP>\&.\&.\&.>"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
