.TH "Dimension::RemoveOneInstance< T, Tuple >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::RemoveOneInstance< T, Tuple > \- Struct to remove one instance of a type from a tuple of types\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP \fBT\fP, \fBtypename\fP \fBTuple\fP>
.br
struct Dimension::RemoveOneInstance< T, Tuple >"Struct to remove one instance of a type from a tuple of types\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
