.TH "Dimension::AddIfUnique< T, Ts >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::AddIfUnique< T, Ts >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DimensionUtilities\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBtype\fP = std::conditional_t<\fBhas_type\fP<\fBT\fP, std::tuple<Ts\&.\&.\&.>>::value, std::tuple<Ts\&.\&.\&.>, std::tuple<Ts\&.\&.\&., \fBT\fP>>"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP , typename\&.\&.\&. Ts> \fBusing\fP \fBDimension::AddIfUnique\fP< \fBT\fP, \fBTs\fP >::type = std::conditional_t<\fBhas_type\fP<\fBT\fP, std::tuple<Ts\&.\&.\&.>>::value, std::tuple<Ts\&.\&.\&.>, std::tuple<Ts\&.\&.\&., \fBT\fP>>"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
