.TH "Dimension::remove_pointer< T * >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::remove_pointer< T * >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DimensionUtilities\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBtype\fP = \fBT\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBusing\fP \fBDimension::remove_pointer\fP< \fBT\fP * >::type = \fBT\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
