.TH "Dimension::tuple_diff< std::tuple< T, restMinuendTypes... >, std::tuple< subtrahendTypes... > >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::tuple_diff< std::tuple< T, restMinuendTypes... >, std::tuple< subtrahendTypes... > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DimensionUtilities\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP , typename\&.\&.\&. restMinuendTypes, typename\&.\&.\&. subtrahendTypes> \fBusing\fP \fBDimension::tuple_diff\fP< std::tuple< \fBT\fP, restMinuendTypes\&.\&.\&. >, std::tuple< subtrahendTypes\&.\&.\&. > >::type"
\fBInitial value:\fP.PP
.nf
 std::conditional_t<
         has_type<T, std::tuple<subtrahendTypes\&.\&.\&.>>::value,
         typename tuple_diff<std::tuple<restMinuendTypes\&.\&.\&.>, typename RemoveOneInstance<T, std::tuple<subtrahendTypes\&.\&.\&.>>::type>::type,
         tuple_cat_t<std::tuple<T>, typename tuple_diff<std::tuple<restMinuendTypes\&.\&.\&.>, std::tuple<subtrahendTypes\&.\&.\&.>>::type>
      >
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
