.TH "Dimension::tuple_diff< std::tuple<>, std::tuple< subtrahendTypes... > >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::tuple_diff< std::tuple<>, std::tuple< subtrahendTypes... > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DimensionUtilities\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBtype\fP = std::tuple<>"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \&.\&.\&. subtrahendTypes> \fBusing\fP \fBDimension::tuple_diff\fP< std::tuple<>, std::tuple< subtrahendTypes\&.\&.\&. > >::type = std::tuple<>"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
