.TH "Dimension::remove_pointer< T >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::remove_pointer< T > \- Struct to return the underlying type a pointer points to\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP \fBT\fP>
.br
struct Dimension::remove_pointer< T >"Struct to return the underlying type a pointer points to\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
