.TH "Dimension::AllUnitSimplifier< NumTuple, DenTuple >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::AllUnitSimplifier< NumTuple, DenTuple >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DimensionUtilities\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBnumTuple\fP = \fBtypename\fP \fBtuple_diff\fP<\fBNumTuple\fP, \fBDenTuple\fP>::type"
.br
.ti -1c
.RI "\fBusing\fP \fBdenTuple\fP = \fBtypename\fP \fBtuple_diff\fP<\fBDenTuple\fP, \fBNumTuple\fP>::type"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBNumTuple\fP , \fBtypename\fP \fBDenTuple\fP > \fBusing\fP \fBDimension::AllUnitSimplifier\fP< \fBNumTuple\fP, \fBDenTuple\fP >::denTuple = \fBtypename\fP \fBtuple_diff\fP<\fBDenTuple\fP, \fBNumTuple\fP>::type"

.SS "template<\fBtypename\fP \fBNumTuple\fP , \fBtypename\fP \fBDenTuple\fP > \fBusing\fP \fBDimension::AllUnitSimplifier\fP< \fBNumTuple\fP, \fBDenTuple\fP >::numTuple = \fBtypename\fP \fBtuple_diff\fP<\fBNumTuple\fP, \fBDenTuple\fP>::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
