.TH "DimensionTest" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DimensionTest
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DimensionTest\&.h>\fP
.PP
Inherits testing::Test\&.
.PP
Inherited by \fBCastOperatorTest\fP, \fBCompoundConversions\fP, \fBFundamentalConversions\fP, \fBOperatorsTest\fP, \fBSimplificationTest\fP, and \fBUtilitiesTest\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP () override"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP () override"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void DimensionTest::SetUp ()\fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.SS "virtual void DimensionTest::TearDown ()\fR [inline]\fP, \fR [override]\fP, \fR [protected]\fP, \fR [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
