.TH "Dimension::has_type< T, Tuple >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::has_type< T, Tuple > \- Struct to check if a tuple of types contains a type\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP \fBT\fP, \fBtypename\fP \fBTuple\fP>
.br
struct Dimension::has_type< T, Tuple >"Struct to check if a tuple of types contains a type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
