.TH "Dimension::MakeCountersImpl< Tuple, UniqueTypes >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::MakeCountersImpl< Tuple, UniqueTypes > \- Implementation of \fBMakeCounters\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP \fBTuple\fP, \fBtypename\fP \fBUniqueTypes\fP>
.br
struct Dimension::MakeCountersImpl< Tuple, UniqueTypes >"Implementation of \fBMakeCounters\fP\&. 


.PP
\fBTodo\fP
.RS 4
Consider updating this to a tuple of pairs rather than tuple of tuples 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
