.TH "Dimension::has_type< T, std::tuple< Us... > >" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::has_type< T, std::tuple< Us... > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <DimensionUtilities\&.h>\fP
.PP
Inherits std::disjunction< std::is_same< std::remove_cv< remove_pointer< T >::type >::type, std::remove_cv< remove_pointer< Us >::type >::type >\&.\&.\&. >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
