.TH "FundamentalConversions" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FundamentalConversions
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <TestFundamentalConversions\&.h>\fP
.PP
Inherits \fBDimensionTest\fP\&.
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBDimensionTest\fP
.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP () override"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP () override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
