.TH "LengthDimension.h" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LengthDimension.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include 'BaseDimension\&.h'\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDimension::LengthUnitFactory\fP"
.br
.RI "\fBUnitFactory\fP templated on \fBLengthUnit\fP\&. "
.ti -1c
.RI "class \fBDimension::LengthUnit\fP"
.br
.RI "\fBLength\fP unit, derived from \fBBaseUnit\fP\&. "
.ti -1c
.RI "class \fBDimension::Length\fP"
.br
.RI "\fBLength\fP dimension, derived from \fBBaseDimension\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDimension\fP"
.br
.ti -1c
.RI "namespace \fBDimension::LengthUnits\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBDimension::LengthTup\fP = std::tuple<\fBLengthUnit\fP*>"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
