.TH "md__r_e_a_d_m_e" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Dimensional 
.PP
 \fBWORK IN PROGRESS\fP
.PP
This library is in very early development and is not yet ready for any form of release\&.
.PP
\fBThe following documentatin is GitLab generated placeholder and is not yet populated\fP
.SH "Description"
.PP
Dimensional is a Physical Unit of Measure library with a heavy emphasis on storing data as a \fBDimension\fP, rather than a Unit\&.
.PP
Using this library, developers may create objects any \fBDimension\fP\&. When creating these objects, the Unit being used must be known, but object is intended to be used from that point forward without the knowledge of the unit used to create the object\&.
.PP
Strong typing is critical in Dimensional; inappropriate operations lead to compile-time errors rather than runtime crashes\&.
.SS "Fundamental and Derived Units"
Dimensions come in two flavors in \fRDimensional\fP - Fundamental and Derived\&.
.PP
Fundamental dimensions are those that are not made up of other dimensions, such as \fRLength\fP, \fRTime\fP, and \fRMass\fP\&.
.PP
Derived dimensions are those that are made up of some number of Fundamental dimensions, like \fRSpeed\fP, \fRAcceleration\fP, and \fRForce\fP
.PP
In Dimensions, a \fBDimension\fP object can be created using any combination of Units, but dedicated Derived dimensions can improve code readibility\&.
.SH "Usage"
.PP
For now, see \fRthe provided unit tests for usage\fP\&.
.PP
\fBDetailed Usage to be added soon\fP
.SH "Local Modifications"
.PP
.SH "Writing Issues"
.PP
.SH "Contributing"
.PP
.SH "License"
.PP
This library is open-source, and is licensed under \fRthe MIT license\fP
.SH "Project status"
.PP
Active development\&.
.PP
This library is still in early development\&. 
