.TH "SpeedDimension.h" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpeedDimension.h
.SH SYNOPSIS
.br
.PP
\fR#include 'BaseDimension\&.h'\fP
.br
\fR#include 'LengthDimension\&.h'\fP
.br
\fR#include 'TimeDimension\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDimension::Speed\fP"
.br
.RI "\fBSpeed\fP dimension, derived from \fBBaseDimension\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDimension\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
