.TH "UnitTest/TestOperators.cpp" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTest/TestOperators.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'TestOperators\&.h'\fP
.br
\fR#include 'TimeDimension\&.h'\fP
.br
\fR#include 'LengthDimension\&.h'\fP
.br
\fR#include 'SpeedDimension\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBOperatorsTest\fP, \fBComparisons\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBOperatorsTest\fP, \fBDimensionMultiplication\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBOperatorsTest\fP, \fBDimensionDivision\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBOperatorsTest\fP, \fBScalarMultiplication\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBOperatorsTest\fP, \fBScalarDivision\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBOperatorsTest\fP, \fBDimensionAddition\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBOperatorsTest\fP, \fBDimensionSubtraction\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBOperatorsTest\fP, \fBComparisons\fP)"

.SS "TEST_F (\fBOperatorsTest\fP, \fBDimensionAddition\fP)"

.SS "TEST_F (\fBOperatorsTest\fP, \fBDimensionDivision\fP)"

.SS "TEST_F (\fBOperatorsTest\fP, \fBDimensionMultiplication\fP)"

.SS "TEST_F (\fBOperatorsTest\fP, \fBDimensionSubtraction\fP)"

.SS "TEST_F (\fBOperatorsTest\fP, \fBScalarDivision\fP)"

.SS "TEST_F (\fBOperatorsTest\fP, \fBScalarMultiplication\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
