.TH "UnitTest/TestUtilities.cpp" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTest/TestUtilities.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'TestUtilities\&.h'\fP
.br
\fR#include 'TimeDimension\&.h'\fP
.br
\fR#include 'LengthDimension\&.h'\fP
.br
\fR#include 'SpeedDimension\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBUtilitiesTest\fP, \fBTest_tuple_diff\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBUtilitiesTest\fP, \fBTest_tuple_diff\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
