.TH "UnitTest/TestCompoundConversions.cpp" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTest/TestCompoundConversions.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'TestCompoundConversions\&.h'\fP
.br
\fR#include 'TimeDimension\&.h'\fP
.br
\fR#include 'LengthDimension\&.h'\fP
.br
\fR#include 'SpeedDimension\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBCompoundConversions\fP, \fBTestSpeed\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBCompoundConversions\fP, \fBTestSpeed\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
