.TH "UnitTest/TestFundamentalConversions.h" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTest/TestFundamentalConversions.h
.SH SYNOPSIS
.br
.PP
\fR#include 'DimensionTest\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFundamentalConversions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
