.TH "UnitTest/TestCastOperators.cpp" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTest/TestCastOperators.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'TestCastOperators\&.h'\fP
.br
\fR#include 'TimeDimension\&.h'\fP
.br
\fR#include 'LengthDimension\&.h'\fP
.br
\fR#include 'SpeedDimension\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBCastOperatorTest\fP, \fBCastSpeed\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBCastOperatorTest\fP, \fBCastLength\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBCastOperatorTest\fP, \fBCastTime\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBCastOperatorTest\fP, \fBCastLength\fP)"

.SS "TEST_F (\fBCastOperatorTest\fP, \fBCastSpeed\fP)"

.SS "TEST_F (\fBCastOperatorTest\fP, \fBCastTime\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
