.TH "UnitTest/TestSimplification.cpp" 3 "Version 0.4" "Dimensional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitTest/TestSimplification.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'TestSimplification\&.h'\fP
.br
\fR#include 'TimeDimension\&.h'\fP
.br
\fR#include 'LengthDimension\&.h'\fP
.br
\fR#include 'SpeedDimension\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBSimplificationTest\fP, \fBSimplificationWithMath\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBSimplificationTest\fP, \fBSimplification\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBSimplificationTest\fP, \fBSimplification\fP)"

.SS "TEST_F (\fBSimplificationTest\fP, \fBSimplificationWithMath\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Dimensional from the source code\&.
