# generated by datamodel-codegen:
#   filename:  unit_schema.json
#   timestamp: 2025-08-31T04:52:15+00:00

from __future__ import annotations

from typing import Annotated, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Rational(RootModel[List]):
    root: Annotated[
        List,
        Field(description='[num, den] exact rational.', max_length=2, min_length=2),
    ]


class SymbolTerm(RootModel[List]):
    root: Annotated[List, Field(max_length=2, min_length=2)]


class FactorObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    r: Annotated[
        Optional[List],
        Field(description='[num, den] exact rational.', max_length=2, min_length=2),
    ] = None
    e10: Annotated[
        Optional[int], Field(description='power of 10 (can be negative)')
    ] = None
    sym: Optional[List[SymbolTerm]] = None


class Factor1(RootModel[List]):
    root: Annotated[
        List,
        Field(
            description='BACK-COMPAT (legacy like [180, "pi"]). Interpret as r=[first,1] and sym=[[second,[-1,1]]].',
            max_length=2,
            min_length=2,
        ),
    ]


class Conversions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    From: Dict[str, Union[FactorObject, Rational, Factor1, float]]
    To: Dict[str, Union[FactorObject, Rational, Factor1, float]]


class UnitDef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Name: str
    Abbreviation: str
    SI_Prefixes: bool
    Conversions_1: Annotated[Optional[Conversions], Field(alias='Conversions')] = None


class UnitsMap(BaseModel):
    pass
    model_config = ConfigDict(
        extra='allow',
    )


class DimExponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Dimension: Annotated[str, Field(min_length=1)]
    Exponent: int


class UnitExponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Unit: Annotated[str, Field(min_length=1)]
    Exponent: int


class HelperUnitDef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Dimension: Annotated[str, Field(min_length=1)]
    Name: str
    Abbreviation: str
    Conversions_1: Annotated[Conversions, Field(alias='Conversions')]


class FundamentalBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Dimension: Annotated[str, Field(min_length=1)]
    Fundamental: Literal[True]
    HasExtras: bool
    BaseUnit: Annotated[str, Field(min_length=1)]
    SI_Prefixes: bool
    Units: Dict[str, UnitDef]


class DerivedBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Dimension: Annotated[str, Field(min_length=1)]
    Fundamental: Literal[False]
    HasExtras: bool
    Definition: Annotated[List[DimExponent], Field(min_length=1)]
    Units: Dict[str, List[UnitExponent]]
    HelperUnits: Dict[str, HelperUnitDef]


class DimensionalUnitsDimensions(
    RootModel[List[Union[FundamentalBlock, DerivedBlock]]]
):
    root: Annotated[
        List[Union[FundamentalBlock, DerivedBlock]],
        Field(title='Dimensional Units & Dimensions'),
    ]
