# generated by datamodel-codegen:
#   filename:  unit_schema.json
#   timestamp: 2025-11-08T15:35:06+00:00

from __future__ import annotations

from typing import Annotated, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Rational(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    num: int
    den: Optional[int] = 1


class SymbolTerm(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[str, Field(min_length=1)]
    exp: Annotated[Optional[Rational], Field()] = {'num': 1, 'den': 1}


class RatioTerm(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base: Rational
    exp: Annotated[Optional[Rational], Field()] = {'num': 1, 'den': 1}


class FactorObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ratio: Annotated[
        Optional[List[RatioTerm]],
        Field(description='List of rational-base terms (default empty).'),
    ] = []
    sym: Annotated[
        Optional[List[SymbolTerm]],
        Field(description='List of symbol-base terms (default empty).'),
    ] = []


class Conversions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    From: Dict[str, FactorObject]
    To: Dict[str, FactorObject]


class UnitDef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Name: str
    Abbreviation: str
    SI_Prefixes: bool
    Conversions_1: Annotated[Optional[Conversions], Field(alias='Conversions')] = None


class UnitsMap(BaseModel):
    pass
    model_config = ConfigDict(
        extra='allow',
    )


class DimExponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Dimension: Annotated[str, Field(min_length=1)]
    Exponent: int


class UnitExponent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Unit: Annotated[str, Field(min_length=1)]
    Exponent: int


class HelperUnitDef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Dimension: Annotated[str, Field(min_length=1)]
    Name: str
    Abbreviation: str
    Conversions_1: Annotated[Conversions, Field(alias='Conversions')]


class FundamentalBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Dimension: Annotated[str, Field(min_length=1)]
    Fundamental: Literal[True]
    HasExtras: bool
    BaseUnit: Annotated[str, Field(min_length=1)]
    SI_Prefixes: bool
    Units: Dict[str, UnitDef]


class DerivedBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Dimension: Annotated[str, Field(min_length=1)]
    Fundamental: Literal[False]
    HasExtras: bool
    Definition: Annotated[List[DimExponent], Field(min_length=1)]
    Units: Dict[str, List[UnitExponent]]
    HelperUnits: Dict[str, HelperUnitDef]


class DimensionalUnitsDimensions(
    RootModel[List[Union[FundamentalBlock, DerivedBlock]]]
):
    root: Annotated[
        List[Union[FundamentalBlock, DerivedBlock]],
        Field(title='Dimensional Units & Dimensions'),
    ]
